# Generated by Django 2.0.1 on 2018-01-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
